### ISSUE TITLE
File icons

### ISSUE THREAD

**Issue by rkalis** [nathanielCherian/vscode-cashscript#3]
I personally use the Material Icons theme, which adds a bunch of icons based on file type to the side bar, see \[1]

It's probably a stretch to get the Material Icons theme to add support for CashScript, but perhaps it is possible to somehow add an icon association to the CashScript extension so that `.cash` files get a nice icon as well (e.g. [₿](https://unicode-table.com/en/20BF/)).

\[1]:
<img width="339" alt="Screen Shot 2021-06-15 at 13 57 55" src="https://user-images.githubusercontent.com/9142187/122048547-b0a6f700-cde1-11eb-9eab-54e6413cec84.png">

**Comment by nathanielCherian** [comment]
File icons were one of the first features I tried to add, unfortunately the vscode api [doesn't support](https://stackoverflow.com/a/47491380) adding fileicons only completely new theme-packs.

One solution is to open a PR to the [seti repository](https://github.com/jesseweed/seti-ui) (one of the default icon packs shipped with vscode). Also by adding ```.cash``` support to the top theme packs on the marketplace ([Material Icons theme](https://github.com/PKief/vscode-material-icon-theme) included). This should cover most users.

Additionally, because the cashscript grammars are already defined here, it may be worth it to look into creating a section in [github linguist](https://github.com/github/linguist) so github will recognize cashscript files in projects and provide better syntax highlighting.

**Comment by rkalis** [comment]
Ah that's what I was afraid of, too bad VS Code doesn't allow you to bundle just an extra icon with an extension!

It's likely that the maintainers of the libraries won't accept a PR for CashScript as it is not popular enough. The linguist repo says that a language generally needs at least 200 unique repos using it, while the seti icons repo says that the VS COde extension for the language needs to have tens of thousands of downloads. Material icons didn't list any requirements, so it might be possible to send a PR there, but I assume they also have some sort of minimum requirements.

Thanks for looking into it, I guess we'll have to wait for CashScript to be a bit more popular ;)
